export default {
    FRONTRIGHT_ANIMATION_INDEX: 0,
    FRONT_ANIMATION_INDEX: 1,
    BACK_ANIMATION_INDEX: 2,
    BACKRIGHT_ANIMATION_INDEX: 3,
    RIGHT_ANIMATION_INDEX: 4,
    LEFT_ANIMATION_INDEX: 5,
    FRONTLEFT_ANIMATION_INDEX: 6,
    BACKLEFT_ANIMATION_INDEX: 2,
    FRONT_IDLE_INDEX: 0,
    BACK_IDLE_INDEX: 0,
    ENTITY: 'entity_000',
    START_ANIMATION_INDEX: 0
}
