export default {
    FRONT_IDLE_INDEX: 4,
    BACK_IDLE_INDEX: 0,
    BACKLEFT_ANIMATION_INDEX: 2,
    BACKRIGHT_ANIMATION_INDEX: 1,
    FRONTLEFT_ANIMATION_INDEX: 5,
    FRONTRIGHT_ANIMATION_INDEX: 3,
    RIGHT_ANIMATION_INDEX: 6,
    LEFT_ANIMATION_INDEX: 7,
    ENTITY: 'Animaciones',
    START_ANIMATION_INDEX: 4
}
